--- !DirTarget
directoryToSaveModels: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/teste/manipulation"
directoryToExportModels: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/teste/output"
pathToTemplateModelsDirectory: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/"
pathToProfile: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/smarty.profile.uml"
pathToProfileConcern: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/concerns.profile.uml"
pathToProfileRelationships: "/media/thaina/Acer/Users/Thainá/Documents/Experimentos/agm_execucao1/agm_50_3000_0.1_layer/output/resources/relationships.profile.uml"
pathToProfilePatterns: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/patterns.profile.uml"