--- !DirTarget
directoryToSaveModels: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles\\experiment\\agm\\teste\\manipulation"
directoryToExportModels: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles\\experiment\\agm\\teste\\output"
pathToTemplateModelsDirectory: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles/agm/"
pathToProfile: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles\\agm\\smarty.profile.uml"
pathToProfileConcern: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles\\agm\\concerns.profile.uml"
pathToProfileRelationships: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles\\agm\\relationships.profile.uml"
pathToProfilePatterns: "C:\\Users\\Thainá\\Documents\\NetBeansProjects\\OPLA-ArchStyles\\agm\\patterns.profile.uml"