--- !DirTarget
directoryToSaveModels: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/teste/manipulation"
directoryToExportModels: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/teste/output"
pathToTemplateModelsDirectory: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/"
pathToProfile: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/smarty.profile.uml"
pathToProfileConcern: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/concerns.profile.uml"
pathToProfileRelationships: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/relationships.profile.uml"
pathToProfilePatterns: "/home/thaina/NetBeansProjects/OPLA-ArchStyles/agm/patterns.profile.uml"